services:
  storage:
    image: redis:7.0.8-alpine
    volumes:
      - ./data:/data

  view:
    image: node:19-alpine
    environment:
      - PORT=3000
      - REDIS_URL=redis://storage
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - .:/app
    command: yarn dev
    depends_on:
      - storage
